// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYp5HHxBXBBAXHX6JOgvaViBUc20a1VsU',
    appId: '1:811146101297:web:b008d14ed530cdc2754b10',
    messagingSenderId: '811146101297',
    projectId: 'sensordataapp-4df04',
    authDomain: 'sensordataapp-4df04.firebaseapp.com',
    storageBucket: 'sensordataapp-4df04.appspot.com',
    measurementId: 'G-125MSD60QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpdEkH0BI6SwN913FdoA72cYegHfgcvK0',
    appId: '1:811146101297:android:a0af2c0e30c667ea754b10',
    messagingSenderId: '811146101297',
    projectId: 'sensordataapp-4df04',
    storageBucket: 'sensordataapp-4df04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefoCG23xs9wuHgD1xtayapuPQZJYMeXI',
    appId: '1:811146101297:ios:3ed9bba994a35d4a754b10',
    messagingSenderId: '811146101297',
    projectId: 'sensordataapp-4df04',
    storageBucket: 'sensordataapp-4df04.appspot.com',
    iosClientId: '811146101297-7ko7i96bmgp44s7sfidoveen77sdr3uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sensorDataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBefoCG23xs9wuHgD1xtayapuPQZJYMeXI',
    appId: '1:811146101297:ios:66525a8659d5d9a0754b10',
    messagingSenderId: '811146101297',
    projectId: 'sensordataapp-4df04',
    storageBucket: 'sensordataapp-4df04.appspot.com',
    iosClientId: '811146101297-46kjkou319b74d0nblkj9gieon69hk1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sensorDataApp.RunnerTests',
  );
}
